FROM python:alpine3.17

WORKDIR /robot

COPY /Stress_Test /robot/

RUN pip install robotframework && pip install robotframework-requests

# CMD robot -d Results ./Login/Login.robot && sleep 5 




